### ISSUE TITLE
Error with Craft 2.5.2724 Beta

### ISSUE THREAD

**Issue by zizther** [wbrowar/craft-content-stats#1]
With the latest version of the 2.5 beta (2.5.2724) I am getting a template error `Impossible to access an attribute ("name") on a null variable`.

`craft/plugins/contentstats/templates/stats.html(12)`

**Comment by wbrowar** [comment]
Weird.. Is it picking up a section that you didn't create through Craft's Sections Settings? I'm trying to figure out how to test for this.

**Comment by zizther** [comment]
You were right, it was the settings still pulling in a deleted section.
Thanks for looking into this.

Works fine in the latest 2.5 beta
