### ISSUE TITLE
Impossible to invoke a method ("getEntryTypes") on a null variable

### ISSUE THREAD

**Issue by modelesque** [wbrowar/craft-content-stats#4]
I had a [stuck task](https://craftcms.com/support/stuck-tasks) after updating the url structure of one of my channels, and when I fixed it, I keep getting this error from your plugin.  I assume it means to say it can't find the entry types anymore from this this particular channel for some reason.  Any thoughts here?  I've tried disabling/enabling and even uninstalling/installing the plugin, but no dice.

And is there some sort of code you'd want to add to check for `entryTypes|length` to avoid getting this error in the future? I can't access my dashboard without disabling the plugin :(

<img width="1438" alt="screen shot 2016-09-13 at 5 21 42 pm" src="https://cloud.githubusercontent.com/assets/13842870/18479949/2687265c-79d7-11e6-9a70-df325f1d74d3.png">

**Comment by wbrowar** [comment]
Hey Ryan, sorry about that. I just pushed up a quick fix. Please pull down the latest and let me know if that works now.
